/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * NinjaExtraAPI
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  TokenResponse,
  UserCreateSchema,
  UserLoginSchema
} from '../ninjaExtraAPI.schemas'



  /**
 * @summary Signup
 */
export const accountsApiSignup = <TData = AxiosResponse<TokenResponse>>(
    userCreateSchema: UserCreateSchema, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://127.0.0.1:8001/api/accounts/signup/`,
      userCreateSchema,options
    );
  }
/**
 * @summary Login
 */
export const accountsApiLogin = <TData = AxiosResponse<TokenResponse>>(
    userLoginSchema: UserLoginSchema, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://127.0.0.1:8001/api/accounts/login/`,
      userLoginSchema,options
    );
  }
export type AccountsApiSignupResult = AxiosResponse<TokenResponse>
export type AccountsApiLoginResult = AxiosResponse<TokenResponse>
