/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * NinjaExtraAPI
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios'
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  WaitlistEntryCreateSchema,
  WaitlistEntryDetailSchema,
  WaitlistEntryListSchema
} from '../ninjaExtraAPI.schemas'



  /**
 * @summary Create Entry
 */
export const waitlistsApiCreateEntry = <TData = AxiosResponse<WaitlistEntryDetailSchema>>(
    waitlistEntryCreateSchema: WaitlistEntryCreateSchema, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `http://127.0.0.1:8001/api/waitlists/`,
      waitlistEntryCreateSchema,options
    );
  }
/**
 * @summary List Waitlist Entries
 */
export const waitlistsApiListWaitlistEntries = <TData = AxiosResponse<WaitlistEntryListSchema[]>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://127.0.0.1:8001/api/waitlists/`,options
    );
  }
/**
 * @summary Update Entry
 */
export const waitlistsApiUpdateEntry = <TData = AxiosResponse<WaitlistEntryDetailSchema>>(
    entryId: number,
    waitlistEntryListSchema: WaitlistEntryListSchema, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.put(
      `http://127.0.0.1:8001/api/waitlists/${entryId}`,
      waitlistEntryListSchema,options
    );
  }
/**
 * @summary Delete Entry
 */
export const waitlistsApiDeleteEntry = <TData = AxiosResponse<void>>(
    entryId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.delete(
      `http://127.0.0.1:8001/api/waitlists/${entryId}`,options
    );
  }
/**
 * @summary Get Waitlist Entry
 */
export const waitlistsApiGetWaitlistEntry = <TData = AxiosResponse<WaitlistEntryDetailSchema>>(
    entryId: number, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `http://127.0.0.1:8001/api/waitlists/${entryId}`,options
    );
  }
export type WaitlistsApiCreateEntryResult = AxiosResponse<WaitlistEntryDetailSchema>
export type WaitlistsApiListWaitlistEntriesResult = AxiosResponse<WaitlistEntryListSchema[]>
export type WaitlistsApiUpdateEntryResult = AxiosResponse<WaitlistEntryDetailSchema>
export type WaitlistsApiDeleteEntryResult = AxiosResponse<void>
export type WaitlistsApiGetWaitlistEntryResult = AxiosResponse<WaitlistEntryDetailSchema>
