/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * NinjaExtraAPI
 * OpenAPI spec version: 1.0.0
 */
export interface WaitlistEntryListSchema {
  email: string;
  id: number;
}

export interface WaitlistEntryCreateSchema {
  email: string;
}

export interface WaitlistEntryDetailSchema {
  email: string;
  id: number;
  timestamp: string;
  updated: string;
}

export interface UserLoginSchema {
  email: string;
  password: string;
}

export type UserCreateSchemaUsername = string | null;

export type UserCreateSchemaPhoneNumber = string | null;

export interface UserCreateSchema {
  email: string;
  password: string;
  phone_number?: UserCreateSchemaPhoneNumber;
  username?: UserCreateSchemaUsername;
}

export interface TokenResponse {
  access: string;
  email: string;
  refresh: string;
}

