import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, Nunito } from "next/font/google";
import "./globals.css";
import Provider from "@/auth/provider/provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const pacificoSans = Pacifico({
  variable: "--font-pacifico-sans",
  subsets: ["latin"],
  weight: "400",
  preload: true,
});

const zainSans = Nunito({
  variable: "--font-nunito-sans",
  subsets: ["latin"],
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${pacificoSans.variable} ${zainSans.variable} antialiased`}
        >
          {children}
        </body>
      </Provider>
    </html>
  );
}
